-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: fb

local flatbuffers = require('flatbuffers')

local C_SkillDataTB = {} -- the module
local C_SkillDataTB_mt = {} -- the class metatable

function C_SkillDataTB.New()
    local o = {}
    setmetatable(o, {__index = C_SkillDataTB_mt})
    return o
end
function C_SkillDataTB.GetRootAsC_SkillDataTB(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = C_SkillDataTB.New()
    o:Init(buf, n + offset)
    return o
end
function C_SkillDataTB_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function C_SkillDataTB_mt:CSkillDataTRS(j)
    local o = self.view:Offset(4)
    if o ~= 0 then
        local x = self.view:Vector(o)
        x = x + ((j-1) * 4)
        x = self.view:Indirect(x)
        local obj = require('fb.C_SkillDataTR').New()
        obj:Init(self.view.bytes, x)
        return obj
    end
end
function C_SkillDataTB_mt:CSkillDataTRSLength()
    local o = self.view:Offset(4)
    if o ~= 0 then
        return self.view:VectorLen(o)
    end
    return 0
end
function C_SkillDataTB.Start(builder) builder:StartObject(1) end
function C_SkillDataTB.AddCSkillDataTRS(builder, CSkillDataTRS) builder:PrependUOffsetTRelativeSlot(0, CSkillDataTRS, 0) end
function C_SkillDataTB.StartCSkillDataTRSVector(builder, numElems) return builder:StartVector(4, numElems, 4) end
function C_SkillDataTB.End(builder) return builder:EndObject() end

return C_SkillDataTB -- return the module