-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: fb

local flatbuffers = require('flatbuffers')

local cskilldataTR = {} -- the module
local cskilldataTR_mt = {} -- the class metatable

function cskilldataTR.New()
    local o = {}
    setmetatable(o, {__index = cskilldataTR_mt})
    return o
end
function cskilldataTR.GetRootAscskilldataTR(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = cskilldataTR.New()
    o:Init(buf, n + offset)
    return o
end
function cskilldataTR_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function cskilldataTR_mt:_id()
    local o = self.view:Offset(4)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Int32, o + self.view.pos)
    end
    return 0
end
function cskilldataTR_mt:Name()
    local o = self.view:Offset(6)
    if o ~= 0 then
        return self.view:String(o + self.view.pos)
    end
end
function cskilldataTR_mt:Description()
    local o = self.view:Offset(8)
    if o ~= 0 then
        return self.view:String(o + self.view.pos)
    end
end
function cskilldataTR_mt:Cooltime()
    local o = self.view:Offset(10)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Int32, o + self.view.pos)
    end
    return 0
end
function cskilldataTR_mt:Costsp()
    local o = self.view:Offset(12)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Int32, o + self.view.pos)
    end
    return 0
end
function cskilldataTR_mt:Attackdistance()
    local o = self.view:Offset(14)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Float32, o + self.view.pos)
    end
    return 0.0
end
function cskilldataTR_mt:Attackangle()
    local o = self.view:Offset(16)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Float32, o + self.view.pos)
    end
    return 0.0
end
function cskilldataTR_mt:Attacktargettags(j)
    local o = self.view:Offset(18)
    if o ~= 0 then
        local a = self.view:Vector(o)
        return self.view:String(a + ((j-1) * 4))
    end
    return ''
end
function cskilldataTR_mt:AttacktargettagsLength()
    local o = self.view:Offset(18)
    if o ~= 0 then
        return self.view:VectorLen(o)
    end
    return 0
end
function cskilldataTR_mt:Impacttype(j)
    local o = self.view:Offset(20)
    if o ~= 0 then
        local a = self.view:Vector(o)
        return self.view:String(a + ((j-1) * 4))
    end
    return ''
end
function cskilldataTR_mt:ImpacttypeLength()
    local o = self.view:Offset(20)
    if o ~= 0 then
        return self.view:VectorLen(o)
    end
    return 0
end
function cskilldataTR_mt:Nextbattlerid()
    local o = self.view:Offset(22)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Int32, o + self.view.pos)
    end
    return 0
end
function cskilldataTR_mt:Atkratio()
    local o = self.view:Offset(24)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Float32, o + self.view.pos)
    end
    return 0.0
end
function cskilldataTR_mt:Durationtime()
    local o = self.view:Offset(26)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Float32, o + self.view.pos)
    end
    return 0.0
end
function cskilldataTR_mt:Atkinterval()
    local o = self.view:Offset(28)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Float32, o + self.view.pos)
    end
    return 0.0
end
function cskilldataTR_mt:Skillprefab()
    local o = self.view:Offset(30)
    if o ~= 0 then
        return self.view:String(o + self.view.pos)
    end
end
function cskilldataTR_mt:Animationname()
    local o = self.view:Offset(32)
    if o ~= 0 then
        return self.view:String(o + self.view.pos)
    end
end
function cskilldataTR_mt:Hitfxprefab()
    local o = self.view:Offset(34)
    if o ~= 0 then
        return self.view:String(o + self.view.pos)
    end
end
function cskilldataTR_mt:Level()
    local o = self.view:Offset(36)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Int32, o + self.view.pos)
    end
    return 0
end
function cskilldataTR_mt:Attacktype()
    local o = self.view:Offset(38)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Int32, o + self.view.pos)
    end
    return 0
end
function cskilldataTR_mt:Selectortype()
    local o = self.view:Offset(40)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Int32, o + self.view.pos)
    end
    return 0
end
function cskilldataTR.Start(builder) builder:StartObject(19) end
function cskilldataTR.Add_id(builder, Id) builder:PrependInt32Slot(0, Id, 0) end
function cskilldataTR.AddName(builder, name) builder:PrependUOffsetTRelativeSlot(1, name, 0) end
function cskilldataTR.AddDescription(builder, description) builder:PrependUOffsetTRelativeSlot(2, description, 0) end
function cskilldataTR.AddCooltime(builder, cooltime) builder:PrependInt32Slot(3, cooltime, 0) end
function cskilldataTR.AddCostsp(builder, costsp) builder:PrependInt32Slot(4, costsp, 0) end
function cskilldataTR.AddAttackdistance(builder, attackdistance) builder:PrependFloat32Slot(5, attackdistance, 0.0) end
function cskilldataTR.AddAttackangle(builder, attackangle) builder:PrependFloat32Slot(6, attackangle, 0.0) end
function cskilldataTR.AddAttacktargettags(builder, attacktargettags) builder:PrependUOffsetTRelativeSlot(7, attacktargettags, 0) end
function cskilldataTR.StartAttacktargettagsVector(builder, numElems) return builder:StartVector(4, numElems, 4) end
function cskilldataTR.AddImpacttype(builder, impacttype) builder:PrependUOffsetTRelativeSlot(8, impacttype, 0) end
function cskilldataTR.StartImpacttypeVector(builder, numElems) return builder:StartVector(4, numElems, 4) end
function cskilldataTR.AddNextbattlerid(builder, nextbattlerid) builder:PrependInt32Slot(9, nextbattlerid, 0) end
function cskilldataTR.AddAtkratio(builder, atkratio) builder:PrependFloat32Slot(10, atkratio, 0.0) end
function cskilldataTR.AddDurationtime(builder, durationtime) builder:PrependFloat32Slot(11, durationtime, 0.0) end
function cskilldataTR.AddAtkinterval(builder, atkinterval) builder:PrependFloat32Slot(12, atkinterval, 0.0) end
function cskilldataTR.AddSkillprefab(builder, skillprefab) builder:PrependUOffsetTRelativeSlot(13, skillprefab, 0) end
function cskilldataTR.AddAnimationname(builder, animationname) builder:PrependUOffsetTRelativeSlot(14, animationname, 0) end
function cskilldataTR.AddHitfxprefab(builder, hitfxprefab) builder:PrependUOffsetTRelativeSlot(15, hitfxprefab, 0) end
function cskilldataTR.AddLevel(builder, level) builder:PrependInt32Slot(16, level, 0) end
function cskilldataTR.AddAttacktype(builder, attacktype) builder:PrependInt32Slot(17, attacktype, 0) end
function cskilldataTR.AddSelectortype(builder, selectortype) builder:PrependInt32Slot(18, selectortype, 0) end
function cskilldataTR.End(builder) return builder:EndObject() end

return cskilldataTR -- return the module